### ISSUE TITLE
Avalon Migration Checklist

### ISSUE THREAD

**Issue by anayram** [ualbertalib/metadata#364]
Avalon migration checklist

- [x] Name fields normalization
- [x] Geo names cleanup
- [x] Dates cleanup
- [ ] Enhancing role descriptions in note fields
- [x] Genre field consistency and usage
- [x] Checking notes field usage
- [x] Custom license terms usage (#361)

Deliverables by July 3 2018:

- [x] Radioactive records for migration testing
- [x] Test migration package (~10% of objects)
- [x] Complete migration package
- [x] Documented migration scripts

**Comment by anayram** [comment]
Will leave role enhancement for later given that batch ingests for Nosotros collection is currently on hold because of transcoding issues.
